import type { Metadata } from "next";
import { CheckCircle2, MonitorSmartphone } from "lucide-react";

export const metadata: Metadata = { title: "Teleconsulta", description: "Atendimento médico por teleconsulta com a Dra. Heloísa Geovana Guedes." };

export default function TeleconsultaPage(){return <>
  <section className="pageHero"><div className="container pageHeroGrid"><div><span className="eyebrow">TELECONSULTA</span><h1>Cuidado médico onde você estiver.</h1><p>A teleconsulta amplia o acesso ao acompanhamento clínico quando o exame físico presencial não é indispensável naquele momento.</p></div><MonitorSmartphone size={92} strokeWidth={1} color="#315e52"/></div></section>
  <section className="section softSection"><div className="container"><div className="sectionHeading"><span className="eyebrow">COMO FUNCIONA</span><h2>Simples, segura e individual.</h2></div><div className="steps"><div className="step"><span className="stepNum">01</span><h3>Agende</h3><p>Entre em contato pelo WhatsApp ou consulte horários disponíveis na Medprev.</p></div><div className="step"><span className="stepNum">02</span><h3>Prepare seus dados</h3><p>Tenha em mãos medicamentos, exames recentes e uma lista das principais dúvidas ou sintomas.</p></div><div className="step"><span className="stepNum">03</span><h3>Realize a consulta</h3><p>A avaliação é feita por videochamada. Se houver necessidade de exame físico, será orientado atendimento presencial.</p></div></div></div></section>
  <section className="section"><div className="container aboutGrid"><div className="aboutCopy"><span className="eyebrow">QUANDO PODE AJUDAR</span><h2>Continuidade sem perder o vínculo.</h2><div className="checkList"><span><CheckCircle2/> Retornos e revisão de exames</span><span><CheckCircle2/> Acompanhamento de condições crônicas estáveis</span><span><CheckCircle2/> Revisão de tratamentos e sintomas</span><span><CheckCircle2/> Orientação sobre necessidade de avaliação presencial</span></div><p className="notice">A teleconsulta não substitui pronto atendimento em situações de urgência ou emergência.</p></div><div className="infoPanel"><h3>Agendamento</h3><p>Você pode conversar diretamente pelo WhatsApp ou verificar a agenda disponível no perfil da Medprev.</p><div className="heroActions"><a className="button" href="https://wa.me/5544998565990" target="_blank" rel="noreferrer">WhatsApp</a><a className="button buttonGhost" href="https://medprev.online/profissionais/heloisa-geovana-guedes-9a89c7d04d6a29639893b5265aeaea40/" target="_blank" rel="noreferrer">Medprev</a></div></div></div></section>
</>}
