import type { Metadata } from "next";
import { Instagram, MapPin, MessageCircle } from "lucide-react";
import { ContactForm } from "@/components/ContactForm";

export const metadata: Metadata = { title: "Contato e agendamento", description: "Agende sua consulta com a Dra. Heloísa Geovana Guedes em São José dos Pinhais ou por teleconsulta." };

export default function ContatoPage(){return <>
  <section className="pageHero"><div className="container"><span className="eyebrow">CONTATO</span><h1>Vamos cuidar da sua saúde?</h1><p>Escolha o canal mais conveniente para agendar ou solicitar informações sobre o atendimento.</p></div></section>
  <section className="section softSection"><div className="container contactGrid"><div className="contactCards"><a className="contactCard" href="https://wa.me/5544998565990" target="_blank" rel="noreferrer"><MessageCircle/><div><strong>WhatsApp</strong><span>(44) 9 9856-5990</span></div></a><a className="contactCard" href="https://www.instagram.com/draheloisaguedes" target="_blank" rel="noreferrer"><Instagram/><div><strong>Instagram</strong><span>@draheloisaguedes</span></div></a><a className="contactCard" href="https://www.google.com/maps/search/?api=1&query=Rua+Marechal+Deodoro+da+Fonseca+261+Sao+Jose+dos+Pinhais" target="_blank" rel="noreferrer"><MapPin/><div><strong>Metropolimed</strong><span>Rua Marechal Deodoro da Fonseca, 261 · Centro · São José dos Pinhais</span></div></a></div><ContactForm/></div></section>
  <section className="section"><div className="container locationGrid"><div><span className="eyebrow">LOCALIZAÇÃO</span><h2>Atendimento presencial</h2><p className="largeText">Metropolimed - Clínica Médica<br/>Rua Marechal Deodoro da Fonseca, 261<br/>Centro · São José dos Pinhais - PR<br/>CEP 83005-350</p><a className="button buttonGhost" href="https://medprev.online/profissionais/heloisa-geovana-guedes-9a89c7d04d6a29639893b5265aeaea40/" target="_blank" rel="noreferrer">Ver agenda na Medprev</a></div><div className="mapFrame"><iframe title="Mapa da Metropolimed" loading="lazy" src="https://www.google.com/maps?q=Rua%20Marechal%20Deodoro%20da%20Fonseca%20261%20S%C3%A3o%20Jos%C3%A9%20dos%20Pinhais&output=embed"/></div></div></section>
</>}
